In [0]:
def relu(Z):
  
  """
  Arguments:
  Z -- output of linear layer, with shape(n,m), n is number of units
  
  Returns:
  A -- relu result of Z
  cache -- 
  """
  
  A=np.maximum(0,Z)
  
  assert(A.shape == Z.shape)
  
  cache = Z
  return A, cache

In [120]:

def relu_backward(dA, cache):
    """
    Implement the backward propagation for a single RELU unit.
 
    Arguments:
    dA -- post-activation gradient, of any shape
    cache -- 'Z' where we store for computing backward propagation efficiently

    Returns:
    dZ -- Gradient of the cost with respect to Z
    """
    
    Z = cache
    dZ = np.array(dA, copy=True) # just converting dz to a correct object.
    
    # When z <= 0, you should set dz to 0 as well. 
    dZ[Z <= 0] = 0
    
    assert (dZ.shape == Z.shape)
    
    return dZ
  
 

array([[0, 1, 3],
       [2, 2, 3],
       [2, 1, 3],
       [5, 1, 3]])

In [0]:
def softmax(Z):
  '''
  implements softmax funciton
  
  Arguments:
  Z -- input as an array of shape(n,1)
  
  Returns:
  A -- softmax result of array z, same shape as z
  cache -- A. 
  '''
  A=np.exp(Z)/np.sum(np.exp(Z),axis=0)
  cache=Z
  assert(A.shape == Z.shape)
  return A, cache

In [50]:
def softmax_to_label(A):
  p=A.argmax(axis=0)
  return p
print(softmax_to_label(q))

[3 1 0]


In [0]:
def softmax_backward(Y, cache):
  """
  softmax backward for 
  
  """
  
  Z = cache
  
  dZ = softmax(Z)-Y 

In [0]:
def cross_entropy(AL, Y):
  """
  Calculate cross entropy
  
  Arguments:
  AL -- output of model:probability vector, shape (10, m)
  Y -- true label vector, shape of (10,m)
  
  Returns:
  cost -- cross entropy cost
  
  """
  
  m=Y.shape[1]
  assert (AL.shape == Y.shape)
  cost = -np.sum(np.log(AL)*Y)/m
  
  #cost =np.squeeze(cost)
  #assert (cost.shape == ())
  return cost

In [0]:
import numpy as np
AL=np.random.rand(10,2)
AL

Y=np.random.rand(10,2)


In [83]:
sum=0
for i,j in zip(AL[:,0],Y[:,0]):
  print(np.log(i)*j)
  sum+=np.log(i)*j
for i,j in zip(AL[:,1],Y[:,1]):
  print(np.log(i)*j)
  sum+=np.log(i)*j
-sum/2

-2.070676304725382
-0.12242334322964535
-0.5337503172670137
-0.4954385158793055
-0.39008039781808346
-0.14470585316615525
-0.10771245757524081
-0.5192014409628475
-0.024243082213134842
-0.8705443534852548
-0.20301065396042672
-0.10858596937551737
-0.07412327842500935
-1.1473955390071593
-0.10819410093309748
-0.047213625645892564
-0.6378015938057204
-0.10422165444358063
-0.0004193959895334778
-0.3486660445891896


4.029203961248596

In [79]:
(-np.dot(Y[:,0],np.log(AL[:,0]).T)-np.dot(Y[:,1],np.log(AL[:,1]).T))/2

4.029203961248594

In [81]:
np.dot(np.log(AL).T,Y)

array([[-5.27877607, -3.02392247],
       [-4.3085474 , -2.77963186]])

In [88]:
cross_entropy(AL,Y)

4.029203961248595

In [0]:
def L_model_backward(AL, Y, caches):
  """
  Arguments:
  AL --probability vector, output of forward prop, shape of (10,m)
  Y -- true label vector, same shape as AL
  caches -- 
  """
  grads={}
  L=len(caches)
  m=AL.shape[1]
  
  dAL = -np.divide(Y,AL)

In [0]:
def initialize_parameters_deep(layer_dims):
  """
  Arguments:
  layer_dims -- python array containing dimensions of each layer
  
  Returns:
  parameters -- dictionary
                Wl -- weight shape of (layer_dims[l], layer_dims[l-1])
                bl -- bias shape of (layer_dims[l],1)
                
  """
  np.random.seed(1)
  parameters = {}
  
  L=len(layer_dims)
  
  for l in np.arange(1,L,1):
    parameters['W'+str(l)] = np.random.rand(layer_dims[l], layer_dims[l-1]) / np.sqrt(layer_dims[l-1])
    parameters['b'+str(l)] = np.zeros((layer_dims[l],1))
  
    assert(parameters['W'+str(l)].shape == (layer_dims[l], layer_dims[l-1]))
    assert(parameters['b'+str(l)].shape == (layer_dims[l], 1))
  
  return parameters

In [0]:
def linear_forward(A, W, b):
  """
  Arguments:
  A -- activation result from layer l-1, shape of (layer_dims[l-1], m)
  W -- weight for layer l shape of (layer_dims[l], layer_dims[l-1])
  b -- bias for layer l shape of (layer_dims[l], 1)
  
  Returns:
  Z -- linear result shape of (layer_dims[l], m)
  cache -- A,W,b 
  """
  
  
  #Z=np.dot(W,A) + b
  
  Z = W.dot(A) +b
  
  assert(Z.shape == (W.shape[0], A.shape[1]) )
  cache = (A, W, b)
  
  return Z, cache
  
  
  

In [204]:
np.random.seed(0)
A1=np.random.randint(5,size =(4,2))
W=np.random.rand(3,4)
b=np.random.rand(3,1)

linear_forward(A1,W,b)

(array([[ 9.24513744,  5.18402155],
        [10.10452066,  4.87593475],
        [ 4.0826652 ,  2.92546433]]), (array([[4, 0],
         [3, 3],
         [3, 1],
         [3, 2]]), array([[0.43758721, 0.891773  , 0.96366276, 0.38344152],
         [0.79172504, 0.52889492, 0.56804456, 0.92559664],
         [0.07103606, 0.0871293 , 0.0202184 , 0.83261985]]), array([[0.77815675],
         [0.87001215],
         [0.97861834]])))

In [0]:
def relu(Z):
  
  """
  Arguments:
  Z -- output of linear layer, with shape(n,m), n is number of units
  
  Returns:
  A -- relu result of Z
  cache -- 
  """
  
  A=np.maximum(0,Z)
  
  assert(A.shape == Z.shape)
  
  cache = Z
  return A, cache

def linear_activation_forward(A_prev, W, b, activation):
  """
  
  Arguments:
  A_prev -- previous A result from layer l-1, shape of (layer_dims[l-1], m)
  W -- weight for layer l shape of (layer_dims[l], layer_dims[l-1])
  b -- bias for layer l shape of (layer_dims[l], 1)
  activation -- relu/softmax
  
  Returns:
  A -- 
  cache -- 
  """
  
  Z, linear_cache = linear_forward(A_prev, W, b)
  
  if activation == "relu":
    A, activation_cache = relu(Z)
  if activation == "softmax":
    A, activation_cache = softmax(Z)
  
  cache = (linear_cache, activation_cache)
  return A, cache

In [219]:
A1

array([[4, 0],
       [3, 3],
       [3, 1],
       [3, 2]])

In [223]:
W.dot(A1)+b

array([[ 9.24513744,  5.18402155],
       [10.10452066,  4.87593475],
       [ 4.0826652 ,  2.92546433]])

In [221]:
b

array([[0.77815675],
       [0.87001215],
       [0.97861834]])

In [246]:
 linear_activation_forward(A1, W, b, "relu")


(array([[ 9.24513744,  5.18402155],
        [10.10452066,  4.87593475],
        [ 4.0826652 ,  2.92546433]]), ((array([[4, 0],
          [3, 3],
          [3, 1],
          [3, 2]]), array([[0.43758721, 0.891773  , 0.96366276, 0.38344152],
          [0.79172504, 0.52889492, 0.56804456, 0.92559664],
          [0.07103606, 0.0871293 , 0.0202184 , 0.83261985]]), array([[0.77815675],
          [0.87001215],
          [0.97861834]])),
  array([[ 9.24513744,  5.18402155],
         [10.10452066,  4.87593475],
         [ 4.0826652 ,  2.92546433]])))

In [0]:
def L_model_forward(X, parameters):
  """
  Arguments:
  X -- input data. shape of 
  parameters -- output from initialize_parameters_deep. dictionary contains:
                Wl -- weight shape of (layer_dims[l], layer_dims[l-1])
                bl -- bias shape of (layer_dims[l],1)
  
  Returns:
  AL -- final output of shape (layer_dims[l], m)
  """
  L = len(parameters)//2
  
  assert(X.shape[0] == parameters['W1'].shape[1])
  
  caches=[]
  
  A_prev = X
  
  for l in np.arange(1,L):
  
    A, linear_activation_cache = linear_activation_forward(A_prev, parameters['W'+str(l)], parameters['b'+str(l)], "relu")
    A_prev = A
    caches.append(linear_activation_cache)
    #print(A_prev)
  AL, linear_activation_cache =  linear_activation_forward(A_prev, parameters['W'+str(L)], parameters['b'+str(L)], "softmax")
  caches.append(linear_activation_cache)
  
  #assert(AL.shape == (,))
  return AL, caches

In [0]:
import numpy as np
layer_dims = np.array([3,3,5,10])
parameters = initialize_parameters_deep(layer_dims)
X=np.array([[1,2,3],[3,3,3]]).T


In [296]:
AL,c = L_model_forward(X, parameters)
AL

array([[0.07723564, 0.06601342],
       [0.12387982, 0.13197515],
       [0.09780823, 0.09122959],
       [0.14598184, 0.18562891],
       [0.083619  , 0.07400222],
       [0.0686272 , 0.05299894],
       [0.08917162, 0.08123063],
       [0.09937175, 0.09373668],
       [0.11341527, 0.12089989],
       [0.10088965, 0.10228456]])

In [0]:
def linear_backward(dZ, cache):
  """
  Arguments:
  dZ -- cost gradient with respect to linear output z (layer l)
  cache  -- 
  
  Returns -- 
  
  
  """