In [48]:
q=np.array([[1,2,2,5],[1,2,1,1],[3,3,3,3]]).T
q

array([[1, 1, 3],
       [2, 2, 3],
       [2, 1, 3],
       [5, 1, 3]])

In [0]:
def softmax(Z):
  '''
  implements softmax funciton
  
  Arguments:
  Z -- input as an array of shape(n,1)
  
  Returns:
  A -- softmax result of array z, same shape as z
  cache -- A. 
  '''
  A=np.exp(Z)/np.sum(np.exp(Z),axis=0)
  cache=Z
  assert(A.shape == Z.shape)
  return A

In [45]:
softmax(q)

array([[0.01638412, 0.1748777 , 0.25      ],
       [0.04453665, 0.47536689, 0.25      ],
       [0.04453665, 0.1748777 , 0.25      ],
       [0.89454258, 0.1748777 , 0.25      ]])

In [50]:
def softmax_to_label(A):
  p=A.argmax(axis=0)
  return p
print(softmax_to_label(q))

[3 1 0]


In [0]:
def softmax_backward(dA, cache):
  
  Z = cache
  
  