In [0]:
def relu(Z):
  
  """
  Arguments:
  Z -- output of linear layer, with shape(n,m), n is number of units
  
  Returns:
  A -- relu result of Z
  cache -- 
  """
  
  A=np.maximum(0,Z)
  
  assert(A.shape == Z.shape)
  
  cache = Z
  return A, cache

In [120]:

def relu_backward(dA, cache):
    """
    Implement the backward propagation for a single RELU unit.
 
    Arguments:
    dA -- post-activation gradient, of any shape
    cache -- 'Z' where we store for computing backward propagation efficiently

    Returns:
    dZ -- Gradient of the cost with respect to Z
    """
    
    Z = cache
    dZ = np.array(dA, copy=True) # just converting dz to a correct object.
    
    # When z <= 0, you should set dz to 0 as well. 
    dZ[Z <= 0] = 0
    
    assert (dZ.shape == Z.shape)
    
    return dZ
  
 

array([[0, 1, 3],
       [2, 2, 3],
       [2, 1, 3],
       [5, 1, 3]])

In [0]:
def softmax(Z):
  '''
  implements softmax funciton
  
  Arguments:
  Z -- input as an array of shape(n,1)
  
  Returns:
  A -- softmax result of array z, same shape as z
  cache -- A. 
  '''
  A=np.exp(Z)/np.sum(np.exp(Z),axis=0)
  cache=Z
  assert(A.shape == Z.shape)
  return A, cache

In [50]:
def softmax_to_label(A):
  p=A.argmax(axis=0)
  return p
print(softmax_to_label(q))

[3 1 0]


In [0]:
def softmax_backward(Y, cache):
  """
  softmax backward for 
  
  """
  
  Z = cache
  
  dZ = softmax(Z)-Y 

In [0]:
def cross_entropy(AL, Y):
  """
  Calculate cross entropy
  
  Arguments:
  AL -- output of model:probability vector, shape (10, m)
  Y -- true label vector, shape of (10,m)
  
  Returns:
  cost -- cross entropy cost
  
  """
  
  m=Y.shape[1]
  assert (AL.shape == Y.shape)
  cost = -np.sum(np.log(AL)*Y)/m
  
  #cost =np.squeeze(cost)
  #assert (cost.shape == ())
  return cost

In [0]:
import numpy as np
AL=np.random.rand(10,2)
AL

Y=np.random.rand(10,2)


In [83]:
sum=0
for i,j in zip(AL[:,0],Y[:,0]):
  print(np.log(i)*j)
  sum+=np.log(i)*j
for i,j in zip(AL[:,1],Y[:,1]):
  print(np.log(i)*j)
  sum+=np.log(i)*j
-sum/2

-2.070676304725382
-0.12242334322964535
-0.5337503172670137
-0.4954385158793055
-0.39008039781808346
-0.14470585316615525
-0.10771245757524081
-0.5192014409628475
-0.024243082213134842
-0.8705443534852548
-0.20301065396042672
-0.10858596937551737
-0.07412327842500935
-1.1473955390071593
-0.10819410093309748
-0.047213625645892564
-0.6378015938057204
-0.10422165444358063
-0.0004193959895334778
-0.3486660445891896


4.029203961248596

In [79]:
(-np.dot(Y[:,0],np.log(AL[:,0]).T)-np.dot(Y[:,1],np.log(AL[:,1]).T))/2

4.029203961248594

In [81]:
np.dot(np.log(AL).T,Y)

array([[-5.27877607, -3.02392247],
       [-4.3085474 , -2.77963186]])

In [88]:
cross_entropy(AL,Y)

4.029203961248595

In [0]:
def L_model_backward(AL, Y, caches):
  """
  Arguments:
  AL --probability vector, output of forward prop, shape of (10,m)
  Y -- true label vector, same shape as AL
  caches -- 
  """
  grads={}
  L=len(caches)
  m=AL.shape[1]
  
  dAL = -np.divide(Y,AL)

In [0]:
def initialize_parameters_deep(layer_dims):
  """
  Arguments:
  layer_dims -- python array containing dimensions of each layer
  
  Returns:
  parameters -- dictionary
                Wl -- weight shape of (layer_dims[l], layer_dims[l-1])
                bl -- bias shape of (layer_dims[l],1)
                
  """
  np.random.seed(1)
  parameters = {}
  
  L=len(layer_dims)
  
  for l in np.arange(1,L,1):
    parameters['W'+str(l)] = np.random.rand(layer_dims[l], layer_dims[l-1]) / np.sqrt(layer_dims[l-1])
    parameters['b'+str(l)] = np.zeros((layer_dims[l],1))
  
    assert(parameters['W'+str(l)].shape == (layer_dims[l], layer_dims[l-1]))
    assert(parameters['b'+str(l)].shape == (layer_dims[l], 1))
  
  return parameters

In [0]:
def linear_forward(A, W, b):
  """
  Arguments:
  A -- activation result from layer l-1, shape of (layer_dims[l-1], m)
  W -- weight for layer l shape of (layer_dims[l], layer_dims[l-1])
  b -- bias for layer l shape of (layer_dims[l], 1)
  
  Returns:
  Z -- linear result shape of (layer_dims[l], m)
  cache -- A,W,b 
  """
  
  
  #Z=np.dot(W,A) + b
  
  Z = W.dot(A) +b
  
  assert(Z.shape == (W.shape[0], A.shape[1]) )
  cache = (A, W, b)
  
  return Z, cache
  
  
  

In [204]:
np.random.seed(0)
A1=np.random.randint(5,size =(4,2))
W=np.random.rand(3,4)
b=np.random.rand(3,1)

linear_forward(A1,W,b)

(array([[ 9.24513744,  5.18402155],
        [10.10452066,  4.87593475],
        [ 4.0826652 ,  2.92546433]]), (array([[4, 0],
         [3, 3],
         [3, 1],
         [3, 2]]), array([[0.43758721, 0.891773  , 0.96366276, 0.38344152],
         [0.79172504, 0.52889492, 0.56804456, 0.92559664],
         [0.07103606, 0.0871293 , 0.0202184 , 0.83261985]]), array([[0.77815675],
         [0.87001215],
         [0.97861834]])))

In [0]:
def relu(Z):
  
  """
  Arguments:
  Z -- output of linear layer, with shape(n,m), n is number of units
  
  Returns:
  A -- relu result of Z
  cache -- 
  """
  
  A=np.maximum(0,Z)
  
  assert(A.shape == Z.shape)
  
  cache = Z
  return A, cache

def linear_activation_forward(A_prev, W, b, activation):
  """
  
  Arguments:
  A_prev -- previous A result from layer l-1, shape of (layer_dims[l-1], m)
  W -- weight for layer l shape of (layer_dims[l], layer_dims[l-1])
  b -- bias for layer l shape of (layer_dims[l], 1)
  activation -- relu/softmax
  
  Returns:
  A -- 
  cache -- 
  """
  
  Z, linear_cache = linear_forward(A_prev, W, b)
  
  if activation == "relu":
    A, activation_cache = relu(Z)
  if activation == "softmax":
    A, activation_cache = softmax(Z)
  
  cache = (linear_cache, activation_cache)
  return A, cache

In [219]:
A1

array([[4, 0],
       [3, 3],
       [3, 1],
       [3, 2]])

In [223]:
W.dot(A1)+b

array([[ 9.24513744,  5.18402155],
       [10.10452066,  4.87593475],
       [ 4.0826652 ,  2.92546433]])

In [221]:
b

array([[0.77815675],
       [0.87001215],
       [0.97861834]])

In [246]:
 linear_activation_forward(A1, W, b, "relu")


(array([[ 9.24513744,  5.18402155],
        [10.10452066,  4.87593475],
        [ 4.0826652 ,  2.92546433]]), ((array([[4, 0],
          [3, 3],
          [3, 1],
          [3, 2]]), array([[0.43758721, 0.891773  , 0.96366276, 0.38344152],
          [0.79172504, 0.52889492, 0.56804456, 0.92559664],
          [0.07103606, 0.0871293 , 0.0202184 , 0.83261985]]), array([[0.77815675],
          [0.87001215],
          [0.97861834]])),
  array([[ 9.24513744,  5.18402155],
         [10.10452066,  4.87593475],
         [ 4.0826652 ,  2.92546433]])))

In [0]:
def L_model_forward(X, parameters):
  """
  Arguments:
  X -- input data. shape of 
  parameters -- output from initialize_parameters_deep. dictionary contains:
                Wl -- weight shape of (layer_dims[l], layer_dims[l-1])
                bl -- bias shape of (layer_dims[l],1)
  
  Returns:
  AL -- final output of shape (layer_dims[l], m)
  """
  L = len(parameters)//2
  
  assert(X.shape[0] == parameters['W1'].shape[1])
  
  caches=[]
  
  A_prev = X
  
  for l in np.arange(1,L):
  
    A, linear_activation_cache = linear_activation_forward(A_prev, parameters['W'+str(l)], parameters['b'+str(l)], "relu")
    A_prev = A
    caches.append(linear_activation_cache)
    #print(A_prev)
  AL, linear_activation_cache =  linear_activation_forward(A_prev, parameters['W'+str(L)], parameters['b'+str(L)], "softmax")
  caches.append(linear_activation_cache)
  
  #assert(AL.shape == (,))
  return AL, caches

In [0]:
import numpy as np
layer_dims = np.array([3,3,5,10])
parameters = initialize_parameters_deep(layer_dims)
X=np.array([[1,2,3],[3,3,3]]).T


In [296]:
AL,c = L_model_forward(X, parameters)
AL

array([[0.07723564, 0.06601342],
       [0.12387982, 0.13197515],
       [0.09780823, 0.09122959],
       [0.14598184, 0.18562891],
       [0.083619  , 0.07400222],
       [0.0686272 , 0.05299894],
       [0.08917162, 0.08123063],
       [0.09937175, 0.09373668],
       [0.11341527, 0.12089989],
       [0.10088965, 0.10228456]])

In [0]:
def linear_backward(dZ, cache):
  """
  Arguments:
  dZ -- cost gradient with respect to linear output z (layer l)
  cache  -- 
  
  Returns -- 
  
  
  """

In [0]:

  

class Network(object):
  
  def __init__(self, layer_dims, X, labels):
    """
    Arguments: layer_dims -- python array containing dimensions of each layer. e.g. np.array[2,5,10]
                          -- input layer = no. of attributes; hidden layer; output layer = no. of classes
               Y -- true vectorized labels, shape (10,m)
               
               caches -- dictionary containing Z for l in (1,L+1),A for l in (0,L+1), Al - activation result for layer l, Zl - linear result for layer l
                      -- with A for layer L being AL, A0=X
    """
    self.X = X
    
    self.labels = labels
    
    self.layer_dims = layer_dims
    
    self.L = len(layer_dims)
    
    self.parameters = {}
    
    self.AL = 0
    
    self.Y = []
    
    self.m = 0
    
    self.grads = {}
    
    self.caches = {}
    
    self.cost=0
    
    self.p = []
    
  def vectorize_label(self):
      #Y=np.zeros((10,1))
      #Y[labels] =1.0
      #return Y
      """
      labels -- tru labels, array, e.g. [1,3,4]

      """
      y_enc = (np.arange(np.max(self.labels) + 1) == self.labels[:, None]).astype(float)
      
      self.Y = y_enc.T
      
      self.m = self.Y.shape[1]
      
    
  def linear_activation_forward(self, A_prev, W, b, activation):
      """
      Arguments:
      A_prev -- previous A result from layer l-1, shape of (layer_dims[l-1], m)
      W -- weight for layer l shape of (layer_dims[l], layer_dims[l-1])
      b -- bias for layer l shape of (layer_dims[l], 1)
      activation -- relu/softmax

      Returns:
      A -- 
      cache -- 
      """

      #Z, linear_cache = linear_forward(A_prev, W, b)
      
      Z = self.linear_forward(A_prev, W, b)

      if activation == "relu":
        #A, activation_cache = relu(Z)
        A = self.relu(Z)
      if activation == "softmax":
        #A, activation_cache = softmax(Z)
        A = self.softmax(Z)

      #cache = (linear_cache, activation_cache)
      return A  
    
  def initialize_parameters_deep(self):
      """
      Arguments:
      layer_dims -- python array containing dimensions of each layer

      Returns:
      parameters -- dictionary
                    Wl -- weight shape of (layer_dims[l], layer_dims[l-1])
                    bl -- bias shape of (layer_dims[l],1)

      """
      np.random.seed(1)
      #self.parameters = {}

      for l in range(1,self.L):
        self.parameters['W'+str(l)] = np.random.rand(self.layer_dims[l], self.layer_dims[l-1]) / np.sqrt(self.layer_dims[l-1])
        self.parameters['b'+str(l)] = np.zeros((self.layer_dims[l],1))

        assert(self.parameters['W'+str(l)].shape == (self.layer_dims[l], self.layer_dims[l-1]))
        assert(self.parameters['b'+str(l)].shape == (self.layer_dims[l], 1))

    
  def linear_forward(self, A, W, b):
      """
      Arguments:
      A -- activation result from layer l-1, shape of (layer_dims[l-1], m)
      W -- weight for layer l shape of (layer_dims[l], layer_dims[l-1])
      b -- bias for layer l shape of (layer_dims[l], 1)

      Returns:
      Z -- linear result shape of (layer_dims[l], m)
      cache -- A,W,b 
      """


      #Z=np.dot(W,A) + b

      Z = W.dot(A) +b

      assert(Z.shape == (W.shape[0], A.shape[1]) )
      #cache = (A, W, b)

      return Z
    
    
  def relu(self, Z):
  
      """
      Arguments:
      Z -- output of linear layer, with shape(n,m), n is number of units

      Returns:
      A -- relu result of Z
      cache -- 
      """

      A=np.maximum(0,Z)

      assert(A.shape == Z.shape)

      #cache = Z
      return A 
    
    
  def softmax(self, Z):
      '''
      implements softmax funciton

      Arguments:
      Z -- input as an array of shape(n,1)

      Returns:
      A -- softmax result of array z, same shape as z
      cache -- A. 
      '''
      A=np.exp(Z)/np.sum(np.exp(Z),axis=0)
      #cache=Z
      assert(A.shape == Z.shape)
      return A
    


    
  def L_model_forward(self):
      """
      Arguments:
      X -- input data. shape of 
      parameters -- output from initialize_parameters_deep. dictionary contains:
                    Wl -- weight shape of (layer_dims[l], layer_dims[l-1])
                    bl -- bias shape of (layer_dims[l],1)

      Returns:
      AL -- final output of shape (layer_dims[l], m)
      """

      assert(self.X.shape[0] == self.parameters['W1'].shape[1])
      
      self.caches["A0"] = self.X

      for l in np.arange(1,self.L-1):

        
        self.caches["Z"+str(l)] = self.linear_forward(self.caches["A"+str(l-1)], self.parameters['W'+str(l)], self.parameters['b'+str(l)])
        
        self.caches["A"+str(l)] = self.relu(self.caches["Z"+str(l)] )

      l+=1
      
      self.caches["Z"+str(l)] = self.linear_forward(self.caches["A"+str(l-1)], self.parameters['W'+str(l)], self.parameters['b'+str(l)])
      
      self.caches["A"+str(l)] = self.softmax(self.caches["Z"+str(l)])

     
      self.AL = self.caches["A"+str(self.L-1)]

      
  def cross_entropy(self):
      """
      Calculate cross entropy

      Arguments:
      AL -- output of model:probability vector, shape (10, m)
      Y -- true label vector, shape of (10,m)

      Returns:
      cost -- cross entropy cost

      """

      assert (self.AL.shape == self.Y.shape)
      self.cost = -np.sum(np.log(self.AL)*self.Y)/self.m

      self.cost =np.squeeze(self.cost)
      #assert (cost.shape == ())
      #return cost
    
    
  def relu_backward(self, dA, Z):
      """
      Implement the backward propagation for a single RELU unit.

      Arguments:
      dA -- post-activation gradient, of any shape
      cache -- 'Z' where we store for computing backward propagation efficiently

      Returns:
      dZ -- Gradient of the cost with respect to Z
      """

      #Z = cache
      dZ = np.array(dA, copy=True) # just converting dz to a correct object.

      # When z <= 0, you should set dz to 0 as well. 
      dZ[Z <= 0] = 0

      assert (dZ.shape == Z.shape)

      return dZ
    
  
  def softmax_backward(self, Z):
      """
      Z -- linear output Z in current layer l 

      """

      dZ = self.softmax(Z)-self.Y
      
      return dZ
    
    
  def linear_backward(self, dZ, A_prev, W, b):
      """
      Implement the linear portion of backward propagation for a single layer (layer l)

      Arguments:
      dZ -- Gradient of the cost with respect to the linear output (of current layer l)
      cache -- tuple of values (A_prev, W, b) coming from the forward propagation in the current layer
      A_prev -- activation result from layer l-1, 

      Returns:
      dA_prev -- Gradient of the cost with respect to the activation (of the previous layer l-1), same shape as A_prev
      dW -- Gradient of the cost with respect to W (current layer l), same shape as W
      db -- Gradient of the cost with respect to b (current layer l), same shape as b
      """
      #A_prev, W, b = cache
      #m = A_prev.shape[1]

      dW = 1./self.m * np.dot(dZ,A_prev.T)
      db = 1./self.m * np.sum(dZ, axis = 1, keepdims = True)
      dA_prev = np.dot(W.T,dZ)

      assert (dA_prev.shape == A_prev.shape)
      assert (dW.shape == W.shape)
      assert (db.shape == b.shape)

      return dA_prev, dW, db
    
    
  def L_model_backward(self):
      """
      Implement the backward propagation for the [LINEAR->RELU] * (L-1) -> LINEAR -> SIGMOID group

      Arguments:
      AL -- probability vector, output of the forward propagation (L_model_forward())
      Y -- true "label" vector (containing 0 if non-cat, 1 if cat)
      caches -- list of caches containing:
                  every cache of linear_activation_forward() with "relu" (there are (L-1) or them, indexes from 0 to L-2)
                  the cache of linear_activation_forward() with "sigmoid" (there is one, index L-1)

      Returns:
      grads -- A dictionary with the gradients
               grads["dA" + str(l)] = ... 
               grads["dW" + str(l)] = ...
               grads["db" + str(l)] = ... 
      """


      #Y = Y.reshape(AL.shape) # after this line, Y is the same shape as AL

      # Initializing the backpropagation
      
      dAL = - np.divide(self.Y, self.AL) 
               
      self.grads["dA"+str(self.L-1)] = dAL

      # Lth layer (SIGMOID -> LINEAR) gradients. Inputs: "AL, Y, caches". Outputs: "grads["dAL"], grads["dWL"], grads["dbL"]
      
      #current_cache = caches[L-1]

               
      self.grads["dZ"+str(self.L-1)] = self.softmax_backward(self.caches["Z"+str(self.L-1)])
               
                              
      self.grads["dA"+str(self.L-2)], self.grads["dW"+str(self.L-1)], self.grads["db"+str(self.L-1)] = self.linear_backward(self.grads["dZ"+str(self.L-1)], self.caches["A"+str(self.L-2)], self.parameters["W"+str(self.L-1)], self.parameters["b"+str(self.L-1)])
               

      for l in reversed(np.arange(1,self.L-1)):
          # lth layer: (RELU -> LINEAR) gradients.
          #current_cache = caches[l]
                                                                               
          self.grads["dZ"+str(l)] = self.relu_backward(self.grads["dA"+str(l)], self.caches["Z"+str(l)])
                                                                               
          self.grads["dA"+str(l-1)], self.grads["dW"+str(l)], self.grads["db"+str(l)] = self.linear_backward(self.grads["dZ"+str(l)], self.caches["A"+str(l-1)], self.parameters["W"+str(l)], self.parameters["b"+str(l)])
                                                                       
                                                                               
  def update_parameters(self, learning_rate):
      """
      Update parameters using gradient descent

      Arguments:
      parameters -- python dictionary containing your parameters 
      grads -- python dictionary containing your gradients, output of L_model_backward

      Returns:
      parameters -- python dictionary containing your updated parameters 
                    parameters["W" + str(l)] = ... 
                    parameters["b" + str(l)] = ...
      """

      #L = len(parameters) // 2 # number of layers in the neural network
      
      

      # Update rule for each parameter. Use a for loop.
      for l in range(self.L-1):
          self.parameters["W" + str(l+1)] = self.parameters["W" + str(l+1)] - learning_rate * self.grads["dW" + str(l+1)]
          self.parameters["b" + str(l+1)] = self.parameters["b" + str(l+1)] - learning_rate * self.grads["db" + str(l+1)]
   




  def predict(self):
      """
      This function is used to predict the results of a  L-layer neural network.

      Arguments:
      X -- data set of examples you would like to label
      parameters -- parameters of the trained model

      Returns:
      p -- predictions for the given dataset X
      """

      self.p=self.AL.argmax(axis=0)


      print("Accuracy: "  + str(np.sum((self.p == self.labels)/self.m)))
      
      #self.accuracy = np.sum((self.p == self.labels)/self.m)
      #return self.p
    
    
  def L_layer_model(self, learning_rate = 0.0075, num_iterations = 1000, print_cost=False):
      
      np.random.seed(1)
      
      costs = []
      
      accuracys = []
      
      self.vectorize_label()
      
      self.initialize_parameters_deep()
      
      
      for i in range(0, num_iterations):  
        
          self.L_model_forward()
          
          self.cross_entropy()
          
          self.L_model_backward()
          
          self.update_parameters(learning_rate)
          
          # Print the cost every 100 training example
          if print_cost and i % 100 == 0:      
            
            
            print ("Cost after iteration %i: %f" %(i, self.cost))
            
            #accuracy = self.predict().accuracy
            #print (accuracy)
            
          if print_cost and i % 100 == 0:

            costs.append(self.cost)
            
            #accuracys.append(accuracy)
            
      self.predict()
        
      # plot the cost
      plt.plot(np.squeeze(costs))
      #plt.plot(np.squeeze(accuracys))
      plt.ylabel('cost')
      plt.xlabel('iterations (per tens)')
      plt.title("Learning rate =" + str(learning_rate))
      plt.show()


    
    

In [55]:
import time
start_time = time.time()

print("--- %s seconds ---" % (time.time() - start_time))

--- 6.4849853515625e-05 seconds ---


In [57]:
from google.colab import files

uploaded = files.upload()

for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))

Saving train_128.h5 to train_128.h5
Saving train_label.h5 to train_label.h5
User uploaded file "train_128.h5" with length 61442144 bytes
User uploaded file "train_label.h5" with length 482144 bytes


(100,)

In [161]:
with h5py.File('train_128.h5','r') as H:
    X = np.copy(H['data']).T
print(len(data[0,:]))
with h5py.File('train_label.h5','r') as H:
    labels = np.copy(H['label'])
print("The first 10 instances: ",label[22],"\n")

X_1000 = X[:,0:1000]
labels_1000 = labels[0:1000]

start_time = time.time()


layer_dims = np.array([128,100,100,100,100,100,10])

case_train = Network(layer_dims,X_1000, labels_1000)

case_train.L_layer_model(num_iterations=1000, print_cost=True)

print("--- %s seconds ---" % (time.time() - start_time))

128
The first 10 instances:  4 

Cost after iteration 0: nan


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:156: RuntimeWarning: overflow encountered in exp
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:156: RuntimeWarning: invalid value encountered in true_divide
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:211: RuntimeWarning: divide by zero encountered in log
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:211: RuntimeWarning: invalid value encountered in multiply
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:303: RuntimeWarning: divide by zero encountered in true_divide
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:303: RuntimeWarning: invalid value encountered in true_divide
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:234: RuntimeWarning: invalid value encountered in less_equal


Cost after iteration 100: nan
Cost after iteration 200: nan
Cost after iteration 300: nan


KeyboardInterrupt: ignored

In [131]:
np.random.randint(10,size=10)

array([1, 6, 3, 2, 2, 6, 2, 7, 3, 3])

In [148]:
case1.p

   self.p=self.AL.argmax(axis=0)


      print("Accuracy: "  + str(np.sum((self.p == self.labels)/self.m)))

(300,)

In [155]:
np.sum(case1.p == case1.labels)

case1.Y.shape

(10, 300)

In [187]:
import numpy as np
import matplotlib.pyplot as plt
import time
start_time = time.time()

test_layer_dims = np.array([25,25,50,5])
test_X=np.random.rand(25,3000)
test_labels= np.random.randint(5,size=3000)


case1 = Network(test_layer_dims , test_X, test_labels)

case1.L_layer_model(learning_rate = 0.0075, num_iterations=5000, print_cost=True)

print("--- %s seconds ---" % (time.time() - start_time))

Cost after iteration 0: 1.921460
Cost after iteration 100: 1.608946
Cost after iteration 200: 1.608930
Cost after iteration 300: 1.608914
Cost after iteration 400: 1.608898
Cost after iteration 500: 1.608882
Cost after iteration 600: 1.608867
Cost after iteration 700: 1.608851
Cost after iteration 800: 1.608835
Cost after iteration 900: 1.608819
Cost after iteration 1000: 1.608804
Cost after iteration 1100: 1.608788
Cost after iteration 1200: 1.608773
Cost after iteration 1300: 1.608757
Cost after iteration 1400: 1.608742
Cost after iteration 1500: 1.608727
Cost after iteration 1600: 1.608711
Cost after iteration 1700: 1.608696
Cost after iteration 1800: 1.608681
Cost after iteration 1900: 1.608665
Cost after iteration 2000: 1.608650
Cost after iteration 2100: 1.608635
Cost after iteration 2200: 1.608620
Cost after iteration 2300: 1.608605
Cost after iteration 2400: 1.608590
Cost after iteration 2500: 1.608575
Cost after iteration 2600: 1.608560
Cost after iteration 2700: 1.608545
Cost

KeyboardInterrupt: ignored

TypeError: ignored

In [69]:
for i in reversed(np.arange(1,5)):
  print(i)

4
3
2
1


In [26]:
range(1,9)

[1, 2, 3, 4, 5, 6, 7, 8]

In [25]:
np.arange(1,4)

array([1, 2, 3])

In [0]:
#back test case
A_prev = X
W = case1.parameters['W1']
b = case1.parameters['b1']
dZ=np.random.rand(3,2)

m = A_prev.shape[1]

dW = 1./m * np.dot(dZ,A_prev.T)
db = 1./m * np.sum(dZ, axis = 1, keepdims = True)
dA_prev = np.dot(W.T,dZ)

assert (dA_prev.shape == A_prev.shape)
assert (dW.shape == W.shape)
assert (db.shape == b.shape)

In [88]:
#softmax back test

Z_prev=np.random.rand(10,2)

dZ = np.exp(Z_prev)/np.sum(np.exp(Z_prev),axis=0)-Y

dZ

array([[ 0.08667124,  0.10417552],
       [ 0.17286902,  0.10163095],
       [ 0.06679216,  0.12914691],
       [-0.91724266,  0.12998553],
       [ 0.09662129,  0.13753244],
       [ 0.13838783,  0.10114531],
       [ 0.07514305,  0.06157375],
       [ 0.07401605,  0.06063485],
       [ 0.07299804,  0.07267717],
       [ 0.13374399, -0.89850242]])

In [83]:
class shit():
  def __init__(self):
    self.cost=0
  
  def addcost(self):
    self.cost=1 
    
m=shit()
m.cost

0